#!/bin/bash
python3 -m venv .venv
source .venv/bin/activate

python3 -m pip install --upgrade pip
python3 -m pip --version

python3 -m pip install -r requirements.txt

pip3 install SpeechRecognition pydub
pip install google-cloud-texttospeech
pip install google-cloud-translate

# gcloud init
# gcloud auth application-default login
