#!/bin/bash

# use the text in a S3 bucket to create an audio file using Polly

# Check if the necessary arguments are provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <s3 URI to the input_file.txt>"
    exit 1
fi

transcription_file_path=$1

# get the text from the S3 bucket
text=$(aws s3 cp s3://$transcription_file_path -)

# create an audio file using Polly
aws polly synthesize-speech --engine neural --language-code de-DE --output-format mp3 --voice-id Daniel  --text "$text" de-DE.mp3