#!/bin/bash

####################################################################################################
# This script transcribes an MP3 file using AWS Transcribe service
# and saves the transcription result to a JSON file.
####################################################################################################

# Check if the necessary arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <input_file.mp3> <output_file.json> <s3_bucket>"
    exit 1
fi

# Assign input and output file names
input_file=$1
output_file=$2
s3_bucket=$3

# Get the default region from AWS configuration
region=$(aws configure get region)

job_name="transcribe-job-$(date +%s)"

# Transcribe the MP3 file using AWS Transcribe
aws transcribe start-transcription-job \
    --region $region \
    --language-code en-US \
    --media MediaFileUri="s3://$s3_bucket/$input_file" \
    --output-bucket $s3_bucket \
    --output-key $output_file \
    --transcription-job-name $job_name > /dev/null

# Check if transcription job started successfully
if [ $? -eq 0 ]; then
    echo "Transcription job started successfully."
    job_status=""
    while [ "$job_status" != "COMPLETED" ]; do
        job_status=$(aws transcribe get-transcription-job --region $region --transcription-job-name $job_name --query 'TranscriptionJob.TranscriptionJobStatus' --output text)
        sleep 5
    done
    echo "Transcription job completed."
    exit 0
else
    echo "Failed to start transcription job."
    exit 1
fi