#!/bin/bash

####################################################################################################
# This script checks if the necessary arguments are provided and translates a transcription file to 
# a target language using AWS Translate.
####################################################################################################

# Check if the necessary arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <transcription.txt> <s3_bucket>"
    exit 1
fi

transcription_file=$1
s3_bucket=$2

# constants
ROLE_NAME=AWSTranslateFullAccessToSpecificS3BucketRole
POLICY_NAME=AWSTranslateFullAccessToSpecificS3Bucket

# Get the default region from AWS configuration
region=$(aws configure get region)


# get arn of the role
ROLE_ARN=$(aws iam get-role --role-name $ROLE_NAME --query 'Role.Arn' --output text)

# check if the role exists
if [ -z "$ROLE_ARN" ]; then
    echo "Role $ROLE_NAME does not exist. Creating the role..."

    aws iam create-policy --policy-name $POLICY_NAME --policy-document '
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Action": [
                    "s3:GetObject"
                ],
                "Resource": [
                    "arn:aws:s3:::'"$s3_bucket"'/*",
                    "arn:aws:s3:::'"$s3_bucket"'/*"
                ],
                "Effect": "Allow"
            },
            {
                "Action": [
                    "s3:ListBucket"
                ],
                "Resource": [
                    "arn:aws:s3:::'"$s3_bucket"'",
                    "arn:aws:s3:::'"$s3_bucket"'"
                ],
                "Effect": "Allow"
            },
            {
                "Action": [
                    "s3:PutObject"
                ],
                "Resource": [
                    "arn:aws:s3:::'"$s3_bucket"'/*"
                ],
                "Effect": "Allow"
            }
        ]
    }
    ' > /dev/null

    aws iam create-role --role-name $ROLE_NAME --assume-role-policy-document '
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "translate.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }    
    ' > /dev/null

    POLICY_ARN=$(aws iam list-policies --query 'Policies[?PolicyName=='"$POLICY_NAME"'].Arn' --output text)

    aws iam attach-role-policy --role-name $ROLE_NAME --policy-arn $POLICY_ARN  > /dev/null

    ROLE_ARN=$(aws iam get-role --role-name $ROLE_NAME --query 'Role.Arn' --output text)
fi

echo "Policy $POLICY_NAME ARN: $POLICY_ARN"
echo "Role $ROLE_NAME ARN: $ROLE_ARN"

# Translate the transcription to the target language
aws translate start-text-translation-job \
    --input-data-config ContentType=text/plain,S3Uri=s3://$s3_bucket/input/translations \
    --output-data-config S3Uri=s3://$s3_bucket/output \
    --source-language-code en \
    --target-language-codes es \
    --job-name "$s3_bucket-translation-job-$(date +%Y%m%d%H%M%S)" \
    --data-access-role-arn $ROLE_ARN

