#!/bin/bash

####################################################################################################
# This script checks if the necessary arguments are provided and translates a transcription file to 
# a target language using AWS Translate.
####################################################################################################

# Check if the necessary arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <transcription.txt> <s3_bucket>"
    exit 1
fi

transcription_file=$1
s3_bucket=$2


# Get the default region from AWS configuration
region=$(aws configure get region)

# Translate the transcription to the target language
aws translate start-text-translation-job \
    --input-data-config "ContentType=text/plain,S3Uri=s3://$s3_bucket/input/translations" \
    --output-data-config "S3Uri=s3://$s3_bucket/output" \
    --source-language-code en \
    --target-language-codes es \
    --job-name "$s3_bucket-translation-job-$(date +%Y%m%d%H%M%S)" \
    --data-access-role-arn $AWS_TRANSLATE_ROLE_ARN > /dev/null

